### ISSUE TITLE
Support for NVMe devices / dm-crypt / LUKS / LVM

### ISSUE THREAD

**Issue by teohhanhui** [Algodev-github/S#2]
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             7.7G     0  7.7G   0% /dev
run             7.8G  2.1M  7.8G   1% /run
/dev/dm-0       468G  220G  225G  50% /
tmpfs           7.8G  209M  7.6G   3% /dev/shm
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
tmpfs           7.8G   46M  7.7G   1% /tmp
/dev/nvme0n1p1  599M   48M  552M   8% /boot/efi
/dev/loop0       55M   55M     0 100% /var/lib/snapd/snap/core18/1668
/dev/loop1      161M  161M     0 100% /var/lib/snapd/snap/gnome-3-28-1804/116
/dev/loop2      157M  157M     0 100% /var/lib/snapd/snap/gnome-3-28-1804/110
/dev/loop4       55M   55M     0 100% /var/lib/snapd/snap/core18/1288
/dev/loop3       92M   92M     0 100% /var/lib/snapd/snap/core/8592
/dev/loop5      256K  256K     0 100% /var/lib/snapd/snap/gtk2-common-themes/9
/dev/loop6       92M   92M     0 100% /var/lib/snapd/snap/core/8689
/dev/loop7       45M   45M     0 100% /var/lib/snapd/snap/gtk-common-themes/1353
/dev/loop8       45M   45M     0 100% /var/lib/snapd/snap/gtk-common-themes/1440
/dev/loop9      256K  256K     0 100% /var/lib/snapd/snap/gtk2-common-themes/5
tmpfs           1.6G  956K  1.6G   1% /run/user/1000
```

```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0         7:0    0  54.7M  1 loop  /var/lib/snapd/snap/core18/1668
loop1         7:1    0 160.2M  1 loop  /var/lib/snapd/snap/gnome-3-28-1804/116
loop2         7:2    0 156.7M  1 loop  /var/lib/snapd/snap/gnome-3-28-1804/110
loop3         7:3    0  91.3M  1 loop  /var/lib/snapd/snap/core/8592
loop4         7:4    0  54.6M  1 loop  /var/lib/snapd/snap/core18/1288
loop5         7:5    0   132K  1 loop  /var/lib/snapd/snap/gtk2-common-themes/9
loop6         7:6    0  91.4M  1 loop  /var/lib/snapd/snap/core/8689
loop7         7:7    0  44.2M  1 loop  /var/lib/snapd/snap/gtk-common-themes/135
loop8         7:8    0  44.9M  1 loop  /var/lib/snapd/snap/gtk-common-themes/144
loop9         7:9    0   132K  1 loop  /var/lib/snapd/snap/gtk2-common-themes/5
nvme0n1     259:0    0   477G  0 disk  
├─nvme0n1p1 259:1    0   600M  0 part  /boot/efi
└─nvme0n1p2 259:2    0 476.4G  0 part  
  └─luks-d57f1a76-74b2-4846-a9ee-7df99b00856a
            254:0    0 476.4G  0 crypt /
```

```
$ lsblk --fs
NAME FSTYPE FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0
     squash 4.0                                                    0   100% /var/lib/s
loop1
     squash 4.0                                                    0   100% /var/lib/s
loop2
     squash 4.0                                                    0   100% /var/lib/s
loop3
     squash 4.0                                                    0   100% /var/lib/s
loop4
     squash 4.0                                                    0   100% /var/lib/s
loop5
     squash 4.0                                                    0   100% /var/lib/s
loop6
     squash 4.0                                                    0   100% /var/lib/s
loop7
     squash 4.0                                                    0   100% /var/lib/s
loop8
     squash 4.0                                                    0   100% /var/lib/s
loop9
     squash 4.0                                                    0   100% /var/lib/s
nvme0n1
│                                                                           
├─nvme0n1p1
│    vfat   FAT32       B12F-419C                             551.2M     8% /boot/efi
└─nvme0n1p2
     crypto 1           d57f1a76-74b2-4846-a9ee-7df99b00856a                
  └─luks-d57f1a76-74b2-4846-a9ee-7df99b00856a
     ext4   1.0         01657f93-ac1a-465b-8913-b526eb411b94  224.7G    47% /
```

```
$ sudo dmsetup ls --target crypt
luks-d57f1a76-74b2-4846-a9ee-7df99b00856a	(254, 0)
```

```
$ sudo lvmdiskscan
  /dev/nvme0n1                                          [    <476.94 GiB] 
  /dev/loop0                                            [      54.64 MiB] 
  /dev/mapper/luks-d57f1a76-74b2-4846-a9ee-7df99b00856a [     476.35 GiB] 
  /dev/nvme0n1p1                                        [     600.00 MiB] 
  /dev/loop1                                            [     160.15 MiB] 
  /dev/nvme0n1p2                                        [     476.35 GiB] 
  /dev/loop2                                            [    <156.68 MiB] 
  /dev/loop3                                            [      91.31 MiB] 
  /dev/loop4                                            [      54.62 MiB] 
  /dev/loop6                                            [     <91.37 MiB] 
  /dev/loop7                                            [     <44.18 MiB] 
  /dev/loop8                                            [      44.88 MiB] 
  1 disk
  11 partitions
  0 LVM physical volume whole disks
  0 LVM physical volumes
```

Trying to run:

    $ ./run_multiple_benchmarks/test_responsiveness.sh

results in:

```
PART=/dev/root
```

which is obviously incorrect.

Anyway, I tried running the benchmark with the following set in `~/.S-config.sh`:

```sh
PART=/dev/dm-0
BACKING_DEVS=nvme0n1
HIGH_LEV_DEV=dm-0
```

which I'm not sure is correct... and commenting out the following line:

https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L97

Results: [results.tar.gz](https://github.com/Algodev-github/S/files/4256436/results.tar.gz)

**Comment by Algodev-github** [comment]
Hi,
sorry for the late reply.  I'm not sure your configuration works
well (it may). The output of the script may probably help me understand it.

At any rate, the right way to tell S which partition you want your
test performed on, is to set TESTD_DEV, in ~/.S-config, to that
partition.

In your case, I guess you should just set
TEST_DEV=nvme0n1p2

For your convenience, I'm pasting the full documentation on that
parameter, as you find it in ~/.S-config.

Before pasting that, let me tell you that any extension to fully
support dm would be warmly welcome!  :)

Thank you for trying this suite,
Paolo

# Set the following parameter to the name or the full path of a device
# or of a partition, if you want to perform tests on that device or
# partition. In the next comments, we assume for simplicity that
# TEST_DEV is set to just the name of a device.
#
# The following two alternatives are handled differently: first, the
# device contains the partition ${TEST_DEV}1 (or ${TEST_DEV}p1,
# depending on the type of device) and ${TEST_DEV}1 contains a mounted
# filesystem; second, the latter compound condition does not hold. In
# the first case, all test files are created in that filesystem. In
# the second case, the execution is simply aborted if the following
# FORMAT parameter is not set to yes. If, instead, FORMAT is set to
# yes, then
# - the device is formatted so as to contain a partition ${TEST_DEV}1
#   or ${TEST_DEV}p1;
# - an ext4 filesystem is made on that partition;
# - that filesystem is mounted.
#
# If you go directly for a partition, then the latter must contain a
# mounted filesystem.
#
# In all succesful cases, all test files are created in the filesystem
# contained in the test partition.
#
# If TEST_DEV is set, then BASE_DIR will be built automatically,
# overriding your possible choice below.
#
# Be careful in setting TEST_DEV manually in case of bcache or
# raids. With these configurations, more then one device is involved.
# The simplest option is to set BASE_DIR to a directory stored on
# these devices, and let the code of the suite automatically detect
# all the involved devices.
TEST_DEV=

**Comment by teohhanhui** [comment]
Here is the output if I reset everything: https://gist.github.com/teohhanhui/4ff932382f58b389534f2ab847182074

Here's some additional information I've just figured out:

https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L263-L265 gives `/dev/mapper/luks-d57f1a76-74b2-4846-a9ee-7df99b00856a`, which is actually correct. It seems to be the `ext4` partition on top of LUKS?

However, https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L267-L269 tries to match from the `df` output and obviously fails.

**Comment by Algodev-github** [comment]
> Il giorno 6 mar 2020, alle ore 18:30, Teoh Han Hui <notifications@github.com> ha scritto:
> 
> Here is the output if I reset everything: https://gist.github.com/teohhanhui/4ff932382f58b389534f2ab847182074
> 

Ok. So this is with default configuration. Does it work if you set TEST_DEV as I suggested, in ~/.S-config?

> Here's some additional information I've just figured out:
> 
> https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L263-L265 gives /dev/mapper/luks-d57f1a76-74b2-4846-a9ee-7df99b00856a, which is actually correct. It seems to be the ext4 partition on top of LUKS?
> 

Or below LUKS :) But yes, it seems correct.

> However, https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L267-L269 tries to match from the df output and obviously fails.

Yes, because this simple parsing code has not been written with LUKS in mind. So, even if it may have worked also for LUKS, with a little luck, it is no surprise that it fails.

Thanks,
Paolo

**Comment by teohhanhui** [comment]
> Does it work if you set TEST_DEV as I suggested, in ~/.S-config?

Unfortunately not. This is what I get instead:

    $ run_multiple_benchmarks/test_responsiveness.sh
    [sudo] password for teohhanhui: 
    Not enough free space for test files in /var/lib/S: I need at least 500MB

I added logging after this line: https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L347 and this is what I get:

```sh
TEST_DEV=nvme0n1
DISK=disk
```

:man_shrugging:

**Comment by paolo-github** [comment]
> Il giorno 6 mar 2020, alle ore 18:44, Teoh Han Hui <notifications@github.com> ha scritto:
> 
> Does it work if you set TEST_DEV as I suggested, in ~/.S-config?
> 
> Unfortunately not. This is what I get instead:
> 
> $ run_multiple_benchmarks/test_responsiveness.sh
> [sudo] password for teohhanhui: 
> Not enough free space for test files in /var/lib/S: I need at least 500MB
> 

Do you have at least 500MB of free space in the partition containing /var/lib/S? Is that directory in the right test partition?

> I added logging after this line: https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L347 and this is what I get:
> 
> TEST_DEV=nvme0n1
> DISK=disk
> 

This is correct. But it doesn't tell us the partition. The partition suffix has certainly been stripped from the string you set, and the partition name has been put in a dedicated parameter (TEST_PARTITION IIRC).

Thanks,
Paolo

**Comment by teohhanhui** [comment]
> Do you have at least 500MB of free space in the partition containing /var/lib/S? Is that directory in the right test partition?

Yes and yes.

Looks like this line is still the culprit: https://github.com/Algodev-github/S/blob/34f913259b1b9c1729cd08f05ff0277d7f1e2738/process_config.sh#L401 as it resets `PART` to `/dev/root`.

**Comment by paolo-github** [comment]
Ok once again, designed without LUKS :(

If you want to invest a little of your time extending it, I'd be glad to help you!

**Comment by teohhanhui** [comment]
Turns out it was a very simple fix. PR incoming!

**Comment by teohhanhui** [comment]
What I've noticed in the results is how the throughput gets reduced to ~30%, but then the latency is also reduced to ~30% (for the `10r-seq` workload).

[results.tar.gz](https://github.com/Algodev-github/S/files/4299796/results.tar.gz)

**Comment by Algodev-github** [comment]
In the line about latency with 10r-seq I read (unit of measure is seconds, for possible other readers of this thread):
# Workload           mq-deadline               kyber                 bfq                none
  10r-seq              2.17575             2.18075               0.736             2.10975

This doesn't seem a 30% reduction, but a reduction of
(2.10975-0.736)/2.10975 = .65 = 65%
compared with the best performing alternative (none).

It is unavoidable that this reduces throughput, because the random workload for starting up gnome-terminal yields a much lower throughput, and only BFQ succeeds in serving that workload so much (to minimize the start-up of gnome-terminal, as minimizing any latency is one of the main goals of BFQ). The other schedulers go on serving the ten sequential readers most of the time, which of course boosts throughput.
